version: '3.9'

services:
  web:
    build: .
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./resources:/var/www/app/resources
  api:
    image: nathanpc/pickle:perl
    restart: unless-stopped
